-- Listing all unique cities where customers are located.
select distinct(customer_city) from customers;

-- counting number of orders placed in 2017:
select count(order_approved_at) from orders where year(order_purchase_timestamp)= 2017;

-- percentage of orders that were paid in installments
SELECT  (sum(case 
when payment_installments >= 1 then 1
else 0 end)*100)/count(*) from payments;

--  number of customers from each state.
select customer_state, count(customer_id) from customers group by customer_state;

-- number of orders per month in 2018.
select monthname(order_purchase_timestamp) as monthorders, count(order_id) from orders where year(order_purchase_timestamp) = 2018 group by monthorders;

-- percentage of total revenue contributed by each product category.
select upper(products.product_category) category, 
round((sum(payments.payment_value)/(select sum(payment_value) from payments))*100,2) sales_percentage
from products join order_items 
on products.product_id = order_items.product_id
join payments 
on payments.order_id = order_items.order_id
group by category order by sales_percentage desc;

-- correlation between product price and the number of times a product has been purchased.
select products.product_id id, count(order_items.product_id), round(avg(order_items.price),2) price from products join 
	order_items on products.product_id=order_items.product_id group by products.product_id ;
    
-- total revenue generated by each seller, and rank them by revenue.
    select *, dense_rank() over(order by revenue desc) 
   from(
   select 
   payments.order_id seller, sum(payments.payment_value) revenue
from 
order_items join payments on order_items.order_id=payments.order_id  group by seller
) as a;

-- moving average of order values for each customer over their order history.
select *, avg(paymnt) over( order by opt rows between unbounded preceding  and current row)
from
(select orders.customer_id cust, orders.order_purchase_timestamp opt, payments.payment_value paymnt from payments join
orders on payments.order_id=orders.order_id ) as aa;


-- cumulative sales per month for each year.
select *,sum(paym) over( order by years, months) from
(select year(orders.order_purchase_timestamp) years, month(orders.order_purchase_timestamp) months, 
sum(payments.payment_value) paym from orders join payments on orders.order_id=payments.order_id 
group by years, months) abb;


-- year-over-year growth rate of total sales.
select years, summ, (summ- lag(summ,1) over(order by years))/lag(summ,1) over(order by years) from
(select year(orders.order_purchase_timestamp) years, round(sum(payments.payment_value),2) summ from orders join payments
on payments.order_id=orders.order_id group by years) as e;


-- retention rate of customers who make another purchase within 6 months of their first purchase.
with a as (
select orders.customer_id idd, min(orders.order_purchase_timestamp) Minpurchase from 
orders  group by idd
),
b as (
    select a.idd iddd, count( distinct orders.order_purchase_timestamp  > Minpurchase) 
  from a join orders on orders.customer_id=a.idd and orders.order_purchase_timestamp> Minpurchase
  and orders.order_purchase_timestamp < date_add(Minpurchase, interval 6 month) group by iddd
  )
select (count(b.iddd)/count(orders.order_purchase_timestamp))*100 from b join orders on orders.customer_id=b.iddd;


-- top 3 customers who spent the most money in each year.
with table1 as	(select  year(orders.order_purchase_timestamp) yearss, orders.customer_id idd, 
    round(sum(payments.payment_value),2) summ, dense_rank() over(partition by year(orders.order_purchase_timestamp)
    order by sum(payments.payment_value) desc) as dkkk
	from orders join payments
	on orders.order_id=payments.order_id  group by yearss, idd order by yearss  )
select * from table1 where table1.dkkk<=3 ;



